# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates 
    get_provisioning_profile
#    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(scheme: "Runner", workspace: "Runner.xcworkspace")
    upload_to_testflight
  end

  desc "Add device to provisioning profiles"
  lane :add_device do
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(
      devices: device_hash
    )
    match(type: "development", app_identifier: development_app_identifier_array, force_for_new_devices: true)
    match(type: "adhoc", app_identifier: adhoc_app_identifier_array, force_for_new_devices: true)  
  end

end


